= CloudBees action: Deploy with OpenShift

Use this action to trigger Red Hat OpenShift, a hybrid cloud platform.
OpenShift uses Linux containers and Kubernetes to manage applications.

This action triggers OpenShift APIs to build and deploy your application, and fetch stdout logs as output.

== Inputs

[cols="3a,1a,1a,4a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `url`
| String
| Yes
| The OpenShift cluster URL.

| `token`
| String
| Yes
| The OpenShift API token.
Must have read/write access.

| `project_name`
| String
| Yes
| The OpenShift project name, a unique identifier for the application environment when building and deployment occurs.

| `repository_name`
| String
| Yes
| The source code repository name

| `repository_config_yaml_paths`
| String
| Yes
| The paths to the configuration files required to build and deploy the application, listed in deployment order.

|===

== Usage example

In your YAML file, add:

[source,yaml]
----
      steps:
      - name: Build and deploy with OpenShift
        uses: https://github.com/cloudbees-io/openshift-invoke-deployment@v1
        with:
          url: ${{ vars.OPENSHIFT_URL }}
          token: ${{ secrets.OPENSHIFT_TOKEN }}
          project_name: unique-openshift-project-name
          repository_name: ${{ vars.REPO_NAME }}
          repository_config_yaml_paths: my-dir/my-config
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
